name: Release Canary

on:
  schedule:
    - cron: "0 3 * * *" # every day at 6AM (GMT+3)
  workflow_dispatch:
    inputs:
      dryRun:
        description: Set true if it is test release
        type: boolean
        required: false
        default: false

env:
  IS_CANARY: true
  IS_DRY_RUN: ${{ github.event.inputs.dryRun }}
  SHA_COMMIT: ${{ github.sha }}
  CANARY_STOP_VERSIONS: ${{ vars.CANARY_STOP_VERSIONS }}

jobs:
  check-is-repository-allowed:
    name: Check repository
    uses: ./.github/workflows/.isAllowedRepository.yaml
    secrets: inherit

  check-if-user-allowed:
    name: Check user
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/.isAllowedPublish.yaml
    secrets: inherit

  publish:
    name: Publish canary packages
    runs-on: ubuntu-latest
    needs:
      - check-is-repository-allowed
      - check-if-user-allowed
    if: ${{success() || (needs.check-if-user-allowed.result == 'skipped' && success())}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: v1.2.5
      - name: Install Dependencies
        run: bun install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: bun scripts/build.ts
      - name: Release canary
        if: ${{ success() }}
        run: bun scripts/release.ts
